pipeline {
    agent any // Specifies that the pipeline can run on any available agent
environment {
        // Jenkins credentials ID for GitHub username + PAT
        GIT_CREDENTIALS = credentials('github')
        TESTNG_JAR = 'lib/testng-7.8.1.jar'
    }
    tools
    {
        jdf'JAVA_HOME'
        maven 'Maven'
    }
    stages {
        stage('Checkout') {
            
                // Checkout your source code from a version control system (e.g., Git)
              steps {
                git branch: 'main',
                    url: 'https://github.com/pkz15/TestngFramework.git',
                    credentialsId: 'github'
            
            }
        }

        stage('Build and Test') {
            steps {
                // Execute Maven clean and test goals to run TestNG tests
                // Assumes your project is a Maven project with TestNG dependencies
                bat 'mvn clean test' 
            }
        }

        stage('Publish TestNG Results') {
            steps {
                // Publish TestNG results using the TestNG Results Plugin
                // The plugin parses the testng-results.xml file generated by TestNG
                testngResults pattern: '**/testng-results.xml' 
            }
        }
    }

    post {
        always {
            // Optional: Clean up workspace after build
            cleanWs() 
        }
        failure {
            // Optional: Send notifications on build failure
            echo 'Build failed! Check logs for details.'
        }
        success {
            // Optional: Send notifications on build success
            echo 'Build successful!'
        }
    }
}
