pipeline {
    agent any // Specifies that the pipeline can run on any available agent

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from a version control system (e.g., Git)
                git 'https://github.com/your-repo/your-project.git' 
            }
        }

        stage('Build and Test') {
            steps {
                // Execute Maven clean and test goals to run TestNG tests
                // Assumes your project is a Maven project with TestNG dependencies
                sh 'mvn clean test' 
            }
        }

        stage('Publish TestNG Results') {
            steps {
                // Publish TestNG results using the TestNG Results Plugin
                // The plugin parses the testng-results.xml file generated by TestNG
                testngResults pattern: '**/testng-results.xml' 
            }
        }
    }

    post {
        always {
            // Optional: Clean up workspace after build
            cleanWs() 
        }
        failure {
            // Optional: Send notifications on build failure
            echo 'Build failed! Check logs for details.'
        }
        success {
            // Optional: Send notifications on build success
            echo 'Build successful!'
        }
    }
}
